import type { baseRu } from './baseTranslations'

export const baseEn: typeof baseRu = {
  aggregateReport: 'Aggregate report',
  teamDirectory: 'Clinic team',
  teamHint: 'Active accounts and roles in your organization.',
  staffName: 'Team member',
  reviewHistory: 'Review history',
  reviewPending: 'Awaiting a radiologist’s review.',
  phantomNotice: 'Synthetic technical phantom, not a patient image. Used to test the DICOM viewer.',
  CASE_VERSION_CONFLICT: 'The data has changed. Refresh the case and try again.',
  SESSION_EXPIRED: 'Your session has expired. Sign in again.',
  QUEUE_FULL: 'The queue is full. Wait for the current checks to finish.',
  VALIDATION_ERROR: 'Check required fields, values and times.',
  MODEL_EXTRACTION_REJECTED:
    'The model response could not be verified against the source text. The document has been saved.',
  DOCUMENT_TEXT_REQUIRED: 'The document has no readable text to extract.',
  DOCUMENT_EXTRACTION_REQUIRES_GGUF_PROFILE:
    'Fact extraction requires the local GGUF profile. Check the model settings.',
  extractWithAI: 'Extract facts · MedGemma',
  extractHint:
    'Each suggestion links to an exact quote. Confirm every fact; dates and active prescriptions are never assumed.',
  modelDownloading: 'Downloading model · integrity check before startup',
  MODEL_SERVER_OFFLINE: 'Start the local MedGemma server.',
  MODEL_SERVER_UNAVAILABLE: 'The local model server is unavailable.',
  MODEL_TIMEOUT: 'The model response timed out.',
  MODEL_OUTPUT_INCOMPLETE: 'The model response is incomplete; no conclusion was published.',
  'DOC-SIDE-01': 'Consistency of laterality across documents',
  'DEMO-ALLERGY-01': 'Substance match in a training example',
  'DEMO-LAB-01': 'Completeness of a laboratory record',
  clinical_lab_restriction: 'Clinical restrictions',
  temporal_eligibility: 'Data available at the time of the decision',
  population: 'Applicability to the case',
  MISSING_REQUIRED_FIELD: 'Confirmed data is missing',
  APPROVED_RULE_CATALOG_REQUIRED: 'An approved rule catalog is required',
  UNKNOWN_AVAILABLE_TIME: 'It is unknown when this information became available',
  OUTSIDE_DEMO_SCOPE: 'The case is outside the scope of this training check',
  MODEL_WEIGHTS_MISSING: 'MedGemma model weights have not been downloaded yet.',
  AI_RUNTIME_MISSING: 'The MedGemma runtime is not installed.',
  MODEL_MEMORY_BUDGET_TOO_SMALL: 'There is not enough free memory for the model.',
  MODEL_CPU_MEMORY_INSUFFICIENT: 'There is not enough RAM to run without a GPU.',
  MODEL_OUTPUT_REJECTED: 'The model response failed format or source validation.',
  AI_NOT_REQUESTED: 'The check ran without an AI request.',
  MODEL_BUSY: 'The model is busy with another check.',
  MODEL_INPUT_TOO_LONG: 'The input exceeds the model’s context window.',
  sourceExcerpt: 'Source excerpt (excerpt:exact quote)',
  draftPrivate: 'Private draft. It is not included in checks.',
  draftSaving: 'Saving draft…',
  draftSaved: 'Draft saved to the server',
  draftRestored: 'Your draft has been restored',
  draftFailed: 'Draft not saved. Check your connection.',
  draftLoadFailed: 'Draft could not be loaded. Reopen the form.',
  workspace: 'Clinical workspace',
  cases: 'Patient overview',
  expert: 'Expert review',
  reports: 'Reports',
  settings: 'System and audit',
  welcome: 'Every decision. Grounded in facts.',
  heroSub: 'Bring clinical context together, verify sources and record your own decision.',
  newCase: 'New case',
  queue: 'Your clinical queue',
  queueSub: 'Cases needing attention, together in one workspace.',
  search: 'Search by case code…',
  demo: 'Demonstration mode',
  demoShort: 'Training data',
  local: 'Local processing',
  total: 'Active cases',
  alerts: 'Under review',
  reviewed: 'Physician responses',
  analyses: 'Checks completed',
  patient: 'Case',
  context: 'Clinical context',
  updated: 'Updated',
  status: 'Status',
  open: 'Open case',
  age: 'Age',
  years: 'years',
  male: 'Male',
  female: 'Female',
  unknown: 'Unknown',
  back: 'Back to queue',
  version: 'Version',
  evidence: 'Evidence',
  analysis: 'Decision review',
  imaging: 'Radiology',
  notes: 'Selected context',
  forecast: 'Risk forecast',
  history: 'Version history',
  overview: 'Overview',
  diagnosis: 'Working conclusion',
  facts: 'Clinical facts',
  confirm: 'Confirm',
  unconfirmed: 'Needs review',
  confirmed: 'Confirmed',
  addFact: 'Add fact',
  source: 'Source',
  sources: 'Sources',
  noData: 'No data yet',
  noDataHint: 'Add a source or clinical fact to continue.',
  manual: 'Enter manually',
  documents: 'Upload documents',
  dmed: 'DMED · demo',
  inputMethod: 'How would you like to add data?',
  manualHint: 'Structured form with source and time.',
  documentsHint: 'PDF, DOCX, TXT · extract and verify data.',
  dmedHint: 'Synthetic import without a live connection.',
  save: 'Save',
  cancel: 'Cancel',
  alias: 'Case code',
  summary: 'Symptoms and context',
  sex: 'Sex',
  key: 'Fact type',
  label: 'Label',
  value: 'Value',
  unit: 'Unit',
  eventTime: 'Event time',
  availableTime: 'When it became known',
  availableUnknown: 'Availability time is unknown',
  assertion: 'Observation status',
  present: 'Documented',
  absent: 'Denied',
  not_documented: 'Not documented',
  provenance: 'Provenance',
  patient_reported: 'Reported by patient',
  paper: 'Paper record',
  document: 'Document',
  dmed_demo: 'DMED (demo)',
  orderStatus: 'Prescription status',
  active: 'Active',
  cancelled: 'Cancelled',
  not_applicable: 'Not applicable',
  confirmFact: 'I have checked the value, units, negation and time',
  addNote: 'Physician’s note',
  noteType: 'Note type',
  noteText: 'Comment',
  decision_rationale: 'Decision rationale',
  alert_response: 'Response to an alert',
  run: 'Start check',
  running: 'In progress',
  current: 'Current data',
  decision_time: 'At the time of the decision',
  cutoff: 'Decision time',
  includeAI: 'Request MedGemma',
  scope: 'Scope of the check',
  scopeText: 'Adults · chest · limited catalog',
  stale: 'Data has changed',
  staleHint: 'This result belongs to an earlier version. Run a new check.',
  partial: 'Partial result',
  queued: 'Queued',
  succeeded: 'Finished',
  failed: 'Failed',
  not_started: 'Awaiting check',
  completed: 'Completed',
  unavailable: 'Unavailable',
  coverage: 'What was checked',
  limitations: 'Limitations',
  aiSummary: 'Second opinion · MedGemma',
  noAI: 'No AI conclusion was generated for this check.',
  noAlerts: 'No alerts in the completed checks.',
  noAlertsHint: 'This does not confirm that all decisions and prescriptions are correct.',
  reviewedBy: 'Physician’s response',
  accepted: 'Accepted for consideration',
  rejected: 'Disagreed',
  information_requested: 'Consultation needed',
  seen: 'Seen',
  closed: 'Closed',
  new: 'New',
  comment: 'Rationale',
  review: 'Save response',
  serious: 'Potential risk',
  clarify: 'Clarify documentation',
  reviewRequired: 'Needs review',
  insufficient: 'Insufficient data',
  rule: 'Rule',
  demoRule: 'Demonstration rule',
  openSource: 'Open source',
  uploaded: 'Source added. Review the extracted fields.',
  upload: 'Choose file',
  identityConsent:
    'The source belongs to this case; the data is synthetic or approved for demonstration.',
  uploadHint: 'PDF / DOCX / TXT, up to 20 MB. Unreadable values remain unknown.',
  download: 'Download original',
  connect: 'Connect demo',
  import: 'Import',
  revoke: 'Revoke access',
  success: 'Standard import',
  denied: 'Access denied',
  disconnected: 'Connection interrupted',
  updatedScenario: 'Updated record',
  identity_mismatch: 'Different patient',
  dmedNotice: 'This is a simulated integration. Real DMED credentials are not requested.',
  inspect: 'Check',
  forecastTitle: 'A forecast starts with a suitable model.',
  forecastHint:
    'Check model availability and data completeness. A number is shown only when a supported calculation is possible.',
  horizon: 'Time horizon',
  year: 'year',
  checkEligibility: 'Check eligibility',
  noRiskModel: 'No validated prediction model is connected.',
  probability: 'Probability',
  missingFields: 'Missing data',
  noProbability: 'Not calculated',
  clinicalNote: 'The physician makes the final decision.',
  system: 'System',
  model: 'Local model',
  modelMissing: 'Model installation needed',
  serviceReady: 'Available',
  technical: 'Technical information',
  logout: 'Sign out',
  signIn: 'Sign in to the workspace',
  loginSubtitle: 'Clinical data. Verifiable evidence. Your decision.',
  email: 'Email',
  password: 'Password',
  demoAccounts: 'Training accounts',
  doctor: 'Attending physician',
  radiologist: 'Radiologist',
  quality: 'Quality officer',
  sender: 'Authorized sender',
  admin: 'Administrator',
  analyst: 'Analyst',
  expertRole: 'Clinical expert',
  notifications: 'Notifications',
  noNotifications: 'No new notifications',
  pathway: 'Clinical decision pathway',
  pathwayText: 'Source → confirmed fact → check → physician’s decision',
  lastActivity: 'Recent changes',
  observe: 'Open',
  all: 'All cases',
  uploadCT: 'Upload DICOM',
  ctNotice: 'View original images and record a radiologist’s conclusion.',
  ctConsent:
    'I have verified that the data is authorized and de-identified, including text embedded in pixels.',
  ctEmpty: 'A workspace for a closer look.',
  ctEmptyHint: 'Add a DICOM study to view images and record the radiologist’s opinion.',
  slice: 'Slice',
  window: 'Window',
  lung: 'Lung',
  soft: 'Soft tissue',
  zoom: 'Zoom',
  visualReview: 'Radiologist’s conclusion',
  clarified: 'Clarified',
  createIncident: 'Refer to an expert',
  reason: 'Reason for review',
  under_review: 'Under review',
  awaiting_explanation: 'Awaiting explanation',
  not_confirmed: 'Not confirmed',
  insufficient_information: 'Insufficient information',
  corrective_actions: 'Corrective actions',
  expertSubtitle: 'Independent assessment, decision context and process improvement.',
  explanation: 'Conclusion and rationale',
  saveDecision: 'Save conclusion',
  createReport: 'Prepare report',
  reportsSubtitle: 'De-identified packages with separate sender approval.',
  purpose: 'Purpose',
  basis: 'Basis',
  preview: 'Preview',
  approve: 'Approve package',
  send: 'Send to test receiver',
  draft: 'Draft',
  approved: 'Approved',
  sent: 'Test submission',
  reportNotice: 'Test transport only. No data is sent to government systems.',
  audit: 'Activity log',
  action: 'Action',
  resource: 'Resource',
  time: 'Time',
  roleAccess: 'This section is not available for your role.',
  saved: 'Saved',
  retry: 'Retry',
  loading: 'Loading…',
  sourceText: 'Original text',
  required: 'Complete this field',
  allFacts: 'All facts',
  pendingFacts: 'Unconfirmed',
  localHint: 'Your data stays within your local infrastructure.',
  sourceCount: 'sources',
  noClinicalRules:
    'The clinical catalog has not been approved yet. Only clearly marked training checks are active.',
  modelSetup:
    'GGUF: scripts/start-model.ps1. Installation: scripts/download_gguf.py. Transformers: scripts/setup-model.ps1.',
  permission: 'Access permissions',
  completeInput: 'Source confirmation is required',
  activeRuns: 'Current processing',
  original: 'Original series',
  noMask: 'No mask available',
  factEdit: 'Edit',
  versionHistory: 'Changes are recorded. Original records remain accessible.',
  dataFreshness: 'Data freshness',
  dateFormatHint: 'Enter the time explicitly; an empty field means unknown.',
  reviewContext: 'Context + evidence',
  fullyLocal: 'LOCAL PROCESSING',
  sourceSummary: 'Facts first. Conclusions next.',
  sourceSummaryHint: 'Every check begins with confirmed data and leads back to its source.',
}
