export const interfaceRu = {
  sourceOcrUnavailable: 'На странице {{page}} нет доступного текста; распознавание OCR не подключено.', DOCX_LOGICAL_BLOCK_PREVIEW_NOT_PAGINATED: 'DOCX показан логическими блоками; номера страниц могут отличаться.', DEMO_INTEGRATION: 'Демонстрационная интеграция',
  interfaceLanguage: 'Язык интерфейса', brandCompact: 'КЛИНИЧЕСКИЙ ИНТЕЛЛЕКТ', brandWorkspace: 'КЛИНИЧЕСКОЕ ПРОСТРАНСТВО', evidenceFirst: 'СНАЧАЛА ПРОВЕРЕННЫЕ ФАКТЫ', workspaceNav: 'РАБОЧЕЕ ПРОСТРАНСТВО', platformName: 'Avilab · Платформа', openMenu: 'Открыть меню', evidenceEngine: 'ОПОРА НА ФАКТЫ', connectedContext: 'ОБЪЕДИНЯЙТЕ КЛИНИЧЕСКИЙ КОНТЕКСТ', connectedCare: 'СВЯЗАННАЯ МЕДИЦИНА', patientContext: 'КОНТЕКСТ ПАЦИЕНТА', demoAdapter: 'ДЕМО-ПОДКЛЮЧЕНИЕ', manualSourceName: 'Ручной ввод', sourceType_manual: 'Ручной ввод', sourceType_note: 'Комментарий врача', sourceType_dmed_demo: 'DMED · демо', sourceType_dmed: 'DMED · демо', dicomUploadLimits: 'DICOM ZIP · до 500 МБ · до 1000 изображений',
  requestFailed: 'Не удалось выполнить запрос. Повторите попытку.', serverError: 'Ошибка сервера. Повторите попытку позже.', recordUnavailable: 'Запись не найдена или недоступна вашему аккаунту.', invalidValue: 'Проверьте значение', invalidEmail: 'Введите корректный адрес электронной почты', validationRequired: 'Заполните обязательное поле', validationMin: 'Минимальное значение: {{value}}', validationMax: 'Максимальное значение: {{value}}', validationShort: 'Минимум символов: {{value}}', validationLong: 'Максимум символов: {{value}}', validationNumber: 'Введите число', validationInteger: 'Введите целое число', validationDate: 'Введите корректную дату и время', validationBool: 'Выберите да или нет',
  field_expected_version: 'Версия записи', field_fact_ids: 'Подтверждённые факты', field_case_id: 'Случай', field_source_id: 'Источник', field_span: 'Цитата', field_name: 'Имя / название', field_phone: 'Телефон', field_clinic_name: 'Название клиники', field_plan_id: 'Тариф', field_payment_method_id: 'Способ оплаты', field_password: 'Пароль', field_email: 'Электронная почта', field_age: 'Возраст', field_sex: 'Пол', field_alias: 'Код случая', field_summary: 'Жалобы и контекст', field_diagnosis: 'Заключение', field_reason: 'Причина', field_comment: 'Комментарий', field_text: 'Текст', field_value: 'Значение', field_unit: 'Единица', field_label: 'Название', field_key: 'Тип факта', field_event_time: 'Время события', field_available_time: 'Время доступности', field_decision_time: 'Время решения', field_confirmed: 'Подтверждение', field_deidentified_confirmed: 'Подтверждение обезличивания', field_identity_confirmed: 'Подтверждение источника', field_role: 'Роль', field_status: 'Статус', field_systolic_bp: 'Систолическое давление', field_total_cholesterol: 'Общий холестерин', field_hdl_cholesterol: 'Холестерин ЛПВП', field_smoker: 'Курение', field_diabetes: 'Диабет', field_treated_bp: 'Лечение давления', field_file: 'Файл',
  formInvalid: 'Проверьте поле «${label}»', formRequired: 'Заполните поле «${label}»', formWhitespace: 'Поле «${label}» не может быть пустым', formEmail: 'Введите корректный адрес электронной почты', formNumber: 'Введите число в поле «${label}»', formInteger: 'Введите целое число в поле «${label}»', formMinLength: '«${label}»: минимум ${min} символов', formMaxLength: '«${label}»: максимум ${max} символов', formLength: '«${label}»: нужно ${len} символов', formRangeLength: '«${label}»: от ${min} до ${max} символов', formMin: '«${label}»: не меньше ${min}', formMax: '«${label}»: не больше ${max}', formRange: '«${label}»: от ${min} до ${max}', formEqual: '«${label}»: значение должно быть ${len}', formEnum: 'Выберите допустимое значение для «${label}»', formDate: 'Введите корректную дату в поле «${label}»', formPattern: 'Проверьте формат поля «${label}»',
  selectPlaceholder: 'Выберите значение', closeWindow: 'Закрыть', clearSelection: 'Очистить выбор', showPassword: 'Показать пароль', hidePassword: 'Скрыть пароль', expandRow: 'Развернуть строку', collapseRow: 'Свернуть строку', tabsOverflow: 'Другие разделы',
}
export const interfaceUz: typeof interfaceRu = {
  sourceOcrUnavailable: '{{page}}-sahifada o‘qiladigan matn yo‘q; OCR ulanmagan.', DOCX_LOGICAL_BLOCK_PREVIEW_NOT_PAGINATED: 'DOCX mantiqiy bloklarda ko‘rsatilgan; sahifa raqamlari farq qilishi mumkin.', DEMO_INTEGRATION: 'Demo integratsiya',
  interfaceLanguage: 'Interfeys tili', brandCompact: 'KLINIK INTELLEKT', brandWorkspace: 'KLINIK ISH MAYDONI', evidenceFirst: 'AVVAL TASDIQLANGAN DALILLAR', workspaceNav: 'ISH MAYDONI', platformName: 'Avilab · Platforma', openMenu: 'Menyuni ochish', evidenceEngine: 'DALILLARGA TAYANADI', connectedContext: 'KLINIK MA’LUMOTLARNI BIRLASHTIRING', connectedCare: 'BOG‘LANGAN TIBBIYOT', patientContext: 'BEMOR KONTEKSTI', demoAdapter: 'DEMO-ULANISH', manualSourceName: 'Qo‘lda kiritilgan', sourceType_manual: 'Qo‘lda kiritilgan', sourceType_note: 'Shifokor izohi', sourceType_dmed_demo: 'DMED · demo', sourceType_dmed: 'DMED · demo', dicomUploadLimits: 'DICOM ZIP · 500 MB gacha · 1000 tagacha tasvir',
  requestFailed: 'So‘rovni bajarib bo‘lmadi. Qayta urinib ko‘ring.', serverError: 'Server xatosi. Birozdan keyin qayta urinib ko‘ring.', recordUnavailable: 'Yozuv topilmadi yoki hisobingiz uchun mavjud emas.', invalidValue: 'Qiymatni tekshiring', invalidEmail: 'To‘g‘ri elektron pochta manzilini kiriting', validationRequired: 'Majburiy maydonni to‘ldiring', validationMin: 'Eng kichik qiymat: {{value}}', validationMax: 'Eng katta qiymat: {{value}}', validationShort: 'Kamida {{value}} ta belgi', validationLong: 'Ko‘pi bilan {{value}} ta belgi', validationNumber: 'Son kiriting', validationInteger: 'Butun son kiriting', validationDate: 'To‘g‘ri sana va vaqtni kiriting', validationBool: 'Ha yoki yo‘qni tanlang',
  field_expected_version: 'Yozuv versiyasi', field_fact_ids: 'Tasdiqlangan faktlar', field_case_id: 'Holat', field_source_id: 'Manba', field_span: 'Iqtibos', field_name: 'Ism / nom', field_phone: 'Telefon', field_clinic_name: 'Klinika nomi', field_plan_id: 'Tarif', field_payment_method_id: 'To‘lov usuli', field_password: 'Parol', field_email: 'Elektron pochta', field_age: 'Yosh', field_sex: 'Jins', field_alias: 'Holat kodi', field_summary: 'Shikoyatlar va kontekst', field_diagnosis: 'Xulosa', field_reason: 'Sabab', field_comment: 'Izoh', field_text: 'Matn', field_value: 'Qiymat', field_unit: 'Birlik', field_label: 'Nom', field_key: 'Fakt turi', field_event_time: 'Hodisa vaqti', field_available_time: 'Ma’lum bo‘lgan vaqt', field_decision_time: 'Qaror vaqti', field_confirmed: 'Tasdiqlash', field_deidentified_confirmed: 'Shaxssizlantirishni tasdiqlash', field_identity_confirmed: 'Manbani tasdiqlash', field_role: 'Rol', field_status: 'Holat', field_systolic_bp: 'Sistolik bosim', field_total_cholesterol: 'Umumiy xolesterin', field_hdl_cholesterol: 'HDL xolesterin', field_smoker: 'Chekish', field_diabetes: 'Diabet', field_treated_bp: 'Bosimni davolash', field_file: 'Fayl',
  formInvalid: '«${label}» maydonini tekshiring', formRequired: '«${label}» maydonini to‘ldiring', formWhitespace: '«${label}» maydoni bo‘sh bo‘lmasligi kerak', formEmail: 'To‘g‘ri elektron pochta manzilini kiriting', formNumber: '«${label}» maydoniga son kiriting', formInteger: '«${label}» maydoniga butun son kiriting', formMinLength: '«${label}»: kamida ${min} ta belgi', formMaxLength: '«${label}»: ko‘pi bilan ${max} ta belgi', formLength: '«${label}»: ${len} ta belgi bo‘lishi kerak', formRangeLength: '«${label}»: ${min}–${max} ta belgi', formMin: '«${label}»: kamida ${min}', formMax: '«${label}»: ko‘pi bilan ${max}', formRange: '«${label}»: ${min}–${max} oralig‘ida', formEqual: '«${label}»: qiymat ${len} bo‘lishi kerak', formEnum: '«${label}» uchun ruxsat etilgan qiymatni tanlang', formDate: '«${label}» maydoniga to‘g‘ri sana kiriting', formPattern: '«${label}» maydoni formatini tekshiring',
  selectPlaceholder: 'Qiymatni tanlang', closeWindow: 'Yopish', clearSelection: 'Tanlovni tozalash', showPassword: 'Parolni ko‘rsatish', hidePassword: 'Parolni yashirish', expandRow: 'Qatorni yoyish', collapseRow: 'Qatorni yig‘ish', tabsOverflow: 'Boshqa bo‘limlar',
}
export const interfaceEn: typeof interfaceRu = {
  sourceOcrUnavailable: 'Page {{page}} has no readable text; OCR is not connected.', DOCX_LOGICAL_BLOCK_PREVIEW_NOT_PAGINATED: 'DOCX is shown as logical blocks; page numbers may differ.', DEMO_INTEGRATION: 'Demonstration integration',
  interfaceLanguage: 'Interface language', brandCompact: 'CLINICAL INTELLIGENCE', brandWorkspace: 'CLINICAL WORKSPACE', evidenceFirst: 'EVIDENCE BEFORE ASSUMPTION', workspaceNav: 'WORKSPACE', platformName: 'Avilab · Platform', openMenu: 'Open menu', evidenceEngine: 'EVIDENCE ENGINE', connectedContext: 'CONNECT THE CLINICAL CONTEXT', connectedCare: 'CONNECTED CARE', patientContext: 'PATIENT CONTEXT', demoAdapter: 'DEMO CONNECTION', manualSourceName: 'Manual entry', sourceType_manual: 'Manual entry', sourceType_note: 'Physician’s note', sourceType_dmed_demo: 'DMED · demo', sourceType_dmed: 'DMED · demo', dicomUploadLimits: 'DICOM ZIP · up to 500 MB · up to 1000 images',
  requestFailed: 'The request could not be completed. Please try again.', serverError: 'Server error. Please try again later.', recordUnavailable: 'The record was not found or is not available to your account.', invalidValue: 'Check this value', invalidEmail: 'Enter a valid email address', validationRequired: 'Complete this required field', validationMin: 'Minimum value: {{value}}', validationMax: 'Maximum value: {{value}}', validationShort: 'At least {{value}} characters', validationLong: 'At most {{value}} characters', validationNumber: 'Enter a number', validationInteger: 'Enter a whole number', validationDate: 'Enter a valid date and time', validationBool: 'Select yes or no',
  field_expected_version: 'Record version', field_fact_ids: 'Confirmed facts', field_case_id: 'Case', field_source_id: 'Source', field_span: 'Quote', field_name: 'Name', field_phone: 'Phone', field_clinic_name: 'Clinic name', field_plan_id: 'Plan', field_payment_method_id: 'Payment method', field_password: 'Password', field_email: 'Email', field_age: 'Age', field_sex: 'Sex', field_alias: 'Case code', field_summary: 'Symptoms and context', field_diagnosis: 'Conclusion', field_reason: 'Reason', field_comment: 'Comment', field_text: 'Text', field_value: 'Value', field_unit: 'Unit', field_label: 'Label', field_key: 'Fact type', field_event_time: 'Event time', field_available_time: 'Availability time', field_decision_time: 'Decision time', field_confirmed: 'Confirmation', field_deidentified_confirmed: 'De-identification confirmation', field_identity_confirmed: 'Source confirmation', field_role: 'Role', field_status: 'Status', field_systolic_bp: 'Systolic blood pressure', field_total_cholesterol: 'Total cholesterol', field_hdl_cholesterol: 'HDL cholesterol', field_smoker: 'Smoking', field_diabetes: 'Diabetes', field_treated_bp: 'Blood pressure treatment', field_file: 'File',
  formInvalid: 'Check the ${label} field', formRequired: 'Complete the ${label} field', formWhitespace: '${label} cannot be empty', formEmail: 'Enter a valid email address', formNumber: 'Enter a number for ${label}', formInteger: 'Enter a whole number for ${label}', formMinLength: '${label}: at least ${min} characters', formMaxLength: '${label}: at most ${max} characters', formLength: '${label}: exactly ${len} characters', formRangeLength: '${label}: ${min}–${max} characters', formMin: '${label}: at least ${min}', formMax: '${label}: at most ${max}', formRange: '${label}: between ${min} and ${max}', formEqual: '${label}: the value must equal ${len}', formEnum: 'Select an allowed value for ${label}', formDate: 'Enter a valid date for ${label}', formPattern: 'Check the format of ${label}',
  selectPlaceholder: 'Select a value', closeWindow: 'Close', clearSelection: 'Clear selection', showPassword: 'Show password', hidePassword: 'Hide password', expandRow: 'Expand row', collapseRow: 'Collapse row', tabsOverflow: 'More sections',
}
