import type { components } from './api/generated'
export type User = Omit<components['schemas']['UserResponse'], 'role'> & { role: 'doctor' | 'radiologist' | 'expert' | 'quality' | 'sender' | 'admin' | 'analyst' | 'owner' | 'developer'; is_clinic_owner?: boolean }
export type Role = User['role']
export type Auth = { user: User; csrf_token: string }
export type CaseCreateInput = components['schemas']['CaseCreate']
export type FactInput = components['schemas']['FactInput']
export interface Fact { id: string; key: string; label: string; value: string | number | null; unit: string | null; assertion: string; provenance: string; source_id: string; span: string; confirmed: boolean; event_time: string | null; available_time: string | null; order_status: string; case_version: number; created_at: string; supersedes?: string }
export interface Source { id: string; name: string; type: string; text: string; pages: { page: number; text: string; locator?: string }[]; sha256?: string; limitations: string[]; created_at: string; case_version: number }
export interface Note { id: string; text: string; note_type: string; provenance: string; event_time: string | null; created_at: string; case_version: number }
export interface ClinicalAlert { reviews?: { id: string; status: string; comment: string; reviewer_name: string; created_at: string }[]; id: string; title: string; description: string; severity: string; source_ids: string[]; fact_ids: string[]; status: string; rule_id: string; demo_only: boolean; case_version: number; created_at: string }
export interface Coverage { completed: string[]; not_evaluable: { check_id: string; reason_code: string; missing_fields: string[] }[] }
export interface EvidenceRef { ref: string; fact_id: string; source_id: string; label: string; key: string; value: string | number | null; unit: string | null; assertion: string }
export interface Readiness { clinical_population_eligible?: boolean; clinical_review_ready: boolean; total_facts: number; confirmed_facts: number; eligible_facts: number; unconfirmed_facts: number; excluded_by_time: number; missing_units: string[]; unknown_times: string[]; potential_conflicts: { key: string; fact_ids: string[] }[]; evidence: EvidenceRef[] }
export interface ClinicalConclusion { id: string; diagnosis: string; rationale: string; status: string; author_name: string; created_at: string; case_version: number; evaluated_version: number }
export interface Run { language?: 'ru' | 'uz' | 'en'; review_focus?: 'documentation' | 'clinical_assessment' | 'radiology' | 'clinical_comparison'; include_ai?: boolean; id: string; run_id: string; case_id: string; case_version: number; status: string; stage: string; is_stale: boolean; mode: string; created_at: string; error_code: string | null; result: { language?: string; provenance?: string; demo_only?: boolean; model_id?: string; alert_ids?: string[]; decision_review?: { version: string; mode: string; decision_time: string | null; evaluated_facts: number; excluded_facts: number; checks: { code: string; status: string; evidence: { fact_id: string; source_id: string; label: string; value: string | number | null; unit: string | null }[] }[] }; image_review?: { observations: string[]; limitations: string[] } | null; series_id?: string; frame_index?: number; center?: number; width?: number; coverage?: Coverage; limitations?: string[]; data_quality?: Readiness; ai?: { assessment?: { status: 'insufficient_data' | 'requires_clinician_review'; differential: { label: string; supporting_refs: string[]; opposing_refs: string[]; verification_needed: string }[]; questions: string[] }; evidence?: EvidenceRef[]; summary: string; limitations: string[]; missing_fields: string[] } | null; rule_catalog_version?: string } }
export interface Forecast { case_version: number; model_id?: string; author_name?: string; inputs?: Record<string, string | number | boolean | null>; id: string; probability: number | null; horizon_years: number; eligibility_status: string; missing_fields: string[]; unsupported_reasons: string[]; created_at: string }
export interface Study { analyses?: Run[]; measurements?: { id: string; label: string; distance_mm: number; series_id: string; frame_index: number; center: number; width: number; points: { x: number; y: number }[]; author_name: string; created_at: string }[]; synthetic_phantom?: boolean; reviews?: { id: string; status: string; comment: string; reviewer_name: string; created_at: string }[]; id: string; name: string; reason: string; mask_available: boolean; series: { id: string; count: number; rows: number; columns: number; spacing: number[] | null; orientation: number[] | null; modality?: string; color?: boolean; window_center?: number; window_width?: number }[] }
export interface Case { clinical_conclusions?: ClinicalConclusion[]; pending_facts?: number; pending_imaging?: number; id: string; alias: string; full_name: string; patient_phone: string; age: number | null; sex: string; summary: string; diagnosis: string; version: number; demo: boolean; created_at: string; updated_at: string; alert_count?: number; latest_status?: string; facts: Fact[]; notes: Note[]; documents: Source[]; alerts: ClinicalAlert[]; analyses: Run[]; forecasts: Forecast[]; studies: Study[] }
export interface CaseList { items: Case[]; total: number; stats: { total: number; alerts: number; reviewed: number; analyses: number } }
export interface Status { demo_mode: boolean; database: string; queue: string; model: { vision_ready?: boolean; model_id: string; revision: string; ready: boolean; loaded: boolean; reason: string | null; quantization: string; backend?: string; download_percent?: number | null; clinical_validation: string }; dmed: string; export_transport: string; ct_model: string; risk_model: string; approved_clinical_rules: number }
export interface Incident { id: string; case_id: string; case_alias: string; reason: string; status: string; version: number; decisions: { explanation: string; status: string; created_at: string; actor_id: string }[]; created_at: string }
export interface Export { id: string; status: string; version: number; purpose: string; basis: string; package: Record<string, string | number | boolean | null>; receipt: { id: string; received_at: string; transport: string } | null; sha256: string; created_at: string }
export type TeamMember = Pick<User, 'id' | 'name' | 'email' | 'role'> & { active: boolean }
export interface Audit { actor_name?: string; id: string; actor_id: string; action: string; resource_id: string; created_at: string }
export interface Notification { id: string; case_id: string; case_alias?: string; case_version: number; status: string; created_at: string; read_by?: string[] }
