export const workflowRu = {
  clinicalReview: 'Диагностический разбор', clinicalReviewHint: 'Подтверждённые наблюдения → проверяемые гипотезы → заключение врача.', clinicalReviewNotice: 'MedGemma предлагает гипотезы для проверки врачом. Это не готовый диагноз; клиническая точность не валидирована.',
  requestClinicalReview: 'Запросить диагностический разбор', clinicalReviewResults: 'Результаты диагностического разбора', recordConclusion: 'Записать заключение врача', clinicalConclusions: 'Заключения врача', clinicalConclusionsHint: 'Сохранённые решения с доказательствами, автором и версией случая.', noConclusions: 'Заключение ещё не записано', clinicalDiagnosis: 'Диагноз / клиническое заключение', clinicianConfirmed: 'Подтверждено врачом', provisional: 'Предварительное', clinicianAttestation: 'Я проверил исходные данные и принимаю ответственность за это клиническое заключение.', evaluatedVersion: 'Оценена версия',
  conflictingEvidence: 'Расхождения', conflictingEvidenceHint: 'В одном временном контексте обнаружены разные значения. Сверьте источники.', draftExcluded: 'Неподтверждённые факты не передаются в AI-анализ.', insufficientDiagnosticData: 'Данных недостаточно для обоснованной диагностической гипотезы.', unconfirmedHypothesis: 'Гипотеза · не подтверждена', supportingEvidence: 'Подтверждающие наблюдения', opposingEvidence: 'Противоречащие наблюдения', verificationNeeded: 'Что уточнить', reviewHypothesis: 'Рассмотреть и записать решение', clarifyingQuestions: 'Вопросы для уточнения',
  editCase: 'Редактировать случай', confirmAll: 'Подтвердить все после сверки', queueFilter: 'Фильтр очереди', eligibilityChecked: 'Проверка доступности выполнена', organizationDetails: 'Организация и профиль', markAllRead: 'Отметить всё прочитанным', refreshStatus: 'Проверить соединение', noSearchResults: 'По этому фильтру случаев нет', sourceDownloaded: 'Файл сохранён',
  INSUFFICIENT_CONFIRMED_EVIDENCE: 'Подтвердите жалобы и хотя бы одно дополнительное наблюдение. При недостатке сведений AI не должен угадывать диагноз.', ANALYSIS_ALREADY_RUNNING: 'Для этого случая уже выполняется проверка. Дождитесь результата или отмените её.', CONFIRMED_EVIDENCE_REQUIRED: 'Выберите актуальные подтверждённые факты этого случая.', CLINICAL_REVIEW_STALE: 'Диагностический разбор устарел. Выполните новый разбор.', CLINICAL_REVIEW_REQUIRES_GGUF_PROFILE: 'Диагностический разбор доступен с локальным GGUF-профилем MedGemma.', CUTOFF_REQUIRED: 'Укажите время исходного решения.', JOB_FAILED: 'Обработка не завершилась. Исходные данные сохранены; повторите запрос.',
  INVALID_CREDENTIALS: 'Проверьте электронную почту и пароль.', RATE_LIMIT: 'Слишком много попыток входа. Подождите минуту.', CSRF_INVALID: 'Сессия изменилась. Войдите снова.', networkError: 'Нет связи с сервером. Проверьте, запущен ли backend.', requestTimeout: 'Сервер не ответил вовремя. Проверьте состояние операции перед повтором.', validationDetails: 'Проверьте поля', searchHint: 'Код, жалобы или заключение…',
}
export const workflowUz: typeof workflowRu = {
  clinicalReview: 'Diagnostik yordam', clinicalReviewHint: 'Tasdiqlangan kuzatuvlar → tekshiriladigan taxminlar → shifokor xulosasi.', clinicalReviewNotice: 'MedGemma shifokor tekshirishi uchun taxminlar taklif qiladi. Bu tayyor tashxis emas; klinik aniqligi validatsiyadan o‘tmagan.',
  requestClinicalReview: 'Diagnostik tahlilni boshlash', clinicalReviewResults: 'Diagnostik tahlil natijalari', recordConclusion: 'Shifokor xulosasini yozish', clinicalConclusions: 'Shifokor xulosalari', clinicalConclusionsHint: 'Dalillar, muallif va holat versiyasi bilan saqlangan qarorlar.', noConclusions: 'Xulosa hali yozilmagan', clinicalDiagnosis: 'Tashxis / klinik xulosa', clinicianConfirmed: 'Shifokor tasdiqlagan', provisional: 'Dastlabki', clinicianAttestation: 'Asl ma’lumotlarni tekshirdim va ushbu klinik xulosa uchun mas’uliyatni o‘z zimmamga olaman.', evaluatedVersion: 'Baholangan versiya',
  conflictingEvidence: 'Tafovutlar', conflictingEvidenceHint: 'Bir vaqt kontekstida turli qiymatlar topildi. Manbalarni solishtiring.', draftExcluded: 'Tasdiqlanmagan faktlar AI tahliliga yuborilmaydi.', insufficientDiagnosticData: 'Asosli diagnostik taxmin uchun ma’lumot yetarli emas.', unconfirmedHypothesis: 'Taxmin · tasdiqlanmagan', supportingEvidence: 'Asos bo‘lgan kuzatuvlar', opposingEvidence: 'Zid kuzatuvlar', verificationNeeded: 'Aniqlashtirish kerak', reviewHypothesis: 'Ko‘rib chiqish va qarorni yozish', clarifyingQuestions: 'Aniqlashtiruvchi savollar',
  editCase: 'Holatni tahrirlash', confirmAll: 'Tekshirgach barchasini tasdiqlash', queueFilter: 'Navbat filtri', eligibilityChecked: 'Mavjudlik tekshiruvi bajarildi', organizationDetails: 'Tashkilot va profil', markAllRead: 'Barchasini o‘qilgan deb belgilash', refreshStatus: 'Ulanishni tekshirish', noSearchResults: 'Bu filtrga mos holat topilmadi', sourceDownloaded: 'Fayl saqlandi',
  INSUFFICIENT_CONFIRMED_EVIDENCE: 'Shikoyat va kamida bitta qo‘shimcha kuzatuvni tasdiqlang. Dalil yetishmasa AI tashxisni taxmin qilmasligi kerak.', ANALYSIS_ALREADY_RUNNING: 'Bu holat bo‘yicha tekshiruv bajarilmoqda. Natijani kuting yoki tekshiruvni bekor qiling.', CONFIRMED_EVIDENCE_REQUIRED: 'Shu holatning joriy tasdiqlangan faktlarini tanlang.', CLINICAL_REVIEW_STALE: 'Diagnostik tahlil eskirgan. Yangi tahlilni boshlang.', CLINICAL_REVIEW_REQUIRES_GGUF_PROFILE: 'Diagnostik yordam lokal MedGemma GGUF profilida ishlaydi.', CUTOFF_REQUIRED: 'Dastlabki qaror vaqtini kiriting.', JOB_FAILED: 'Tahlil yakunlanmadi. Asl ma’lumotlar saqlangan; so‘rovni takrorlang.',
  INVALID_CREDENTIALS: 'Elektron pochta va parolni tekshiring.', RATE_LIMIT: 'Kirish urinishlari ko‘p. Bir daqiqa kuting.', CSRF_INVALID: 'Sessiya o‘zgargan. Qayta kiring.', networkError: 'Server bilan aloqa yo‘q. Backend ishga tushganini tekshiring.', requestTimeout: 'Server vaqtida javob bermadi. Takrorlashdan oldin amal holatini tekshiring.', validationDetails: 'Maydonlarni tekshiring', searchHint: 'Kod, shikoyat yoki xulosa…',
}
