import { test, expect } from '@playwright/test'

test('document evidence, private autosave and Uzbek interface', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Войти в пространство', exact: true }).click()
  await page.getByRole('button', { name: 'Новый случай', exact: true }).click()
  await page.getByLabel('Код случая').fill('E2E-DOC-' + Date.now())
  await page.getByLabel('Возраст', { exact: true }).fill('45')
  await page.getByRole('button', { name: 'Сохранить', exact: true }).click()
  await page.getByRole('button', { name: 'Загрузить документы' }).click()
  const upload = page.getByRole('dialog')
  await upload.getByRole('checkbox').check()
  await upload.locator('input[type=file]').setInputFiles('../demo/clinical-record.txt')
  await expect(page.getByText('clinical-record.txt', { exact: true })).toBeVisible()
  await page.getByText('clinical-record.txt', { exact: true }).click()
  await expect(page.locator('.source-paper')).toContainText('allergy.substance=DEMO-A')
  await page.getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('tab', { name: 'Избранный контекст', exact: true }).click()
  await page.getByRole('button', { name: 'Комментарий врача', exact: true }).first().click()
  await page.getByLabel('Комментарий', { exact: true }).fill('E2E private draft — original evidence retained.')
  await expect(page.getByText('Черновик сохранён на сервере', { exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('tab', { name: 'Избранный контекст', exact: true }).click()
  await page.getByRole('button', { name: 'Комментарий врача', exact: true }).first().click()
  await expect(page.getByLabel('Комментарий', { exact: true })).toHaveValue('E2E private draft — original evidence retained.')
  await page.getByRole('button', { name: 'Сохранить', exact: true }).click()
  await expect(page.locator('.note-card')).toContainText('E2E private draft')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.locator('.language .ant-select-selector').click()
  await page.getByText('UZ', { exact: true }).last().click()
  await expect(page.getByRole('tab', { name: 'Dalillar', exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/case-uzbek.png', fullPage: true })
})
