import { test, expect } from '@playwright/test'

test('notifications: mark all persists, failed requests retain unread state, individual items open their case', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('aniq-language', 'uz'))
  const login = await page.request.post('/api/v1/auth/login', { data: { email: 'doctor@demo.aniq', password: 'AniqDemo!2026' } })
  expect(login.ok()).toBeTruthy()
  const auth = await login.json()
  const headers = () => ({ 'X-CSRF-Token': auth.csrf_token, 'Idempotency-Key': crypto.randomUUID() })
  const created = await page.request.post('/api/v1/cases', { headers: headers(), data: { full_name: `Synthetic Notification Patient ${Date.now()}`, age: 45, sex: 'male' } })
  expect(created.status()).toBe(201)
  let clinicalCase = await created.json()
  const analyse = async () => {
    const response = await page.request.post(`/api/v1/cases/${clinicalCase.id}/analyses`, { headers: headers(), data: { expected_version: clinicalCase.version, include_ai: false } })
    expect(response.status()).toBe(202)
  }
  await analyse()
  await page.goto('/cases')
  const trigger = page.locator('.notification-trigger')
  await expect(trigger).toHaveAttribute('aria-label', /o‘qilmagan/)
  await trigger.click()
  const panel = page.getByRole('dialog', { name: 'Bildirishnomalar', exact: true })
  const readAll = panel.getByRole('button', { name: 'Hammasini o‘qish', exact: true })
  await expect(readAll).toBeEnabled()
  await page.route('**/api/v1/notifications/read-all', route => route.fulfill({ status: 503, json: { error: { code: 'TEST_UNAVAILABLE', message: 'Test connection failure' } } }))
  await readAll.click()
  await expect(page.getByText('So‘rovni bajarib bo‘lmadi. Qayta urinib ko‘ring. (TEST_UNAVAILABLE)', { exact: true })).toBeVisible()
  await expect(readAll).toBeEnabled()
  expect((await (await page.request.get('/api/v1/notifications')).json()).unread_count).toBeGreaterThan(0)
  await page.unroute('**/api/v1/notifications/read-all')
  await readAll.click()
  await expect(panel.getByText('Hammasi o‘qilgan', { exact: true })).toBeVisible()
  await expect(readAll).toBeDisabled()
  expect((await (await page.request.get('/api/v1/notifications')).json()).unread_count).toBe(0)
  await page.reload()
  await trigger.click()
  await expect(readAll).toBeDisabled()
  await page.keyboard.press('Escape')
  await expect(panel).toBeHidden()
  await expect(trigger).toBeFocused()

  // An identical analysis is deduplicated; a new case produces a new event.
  const nextCase = await page.request.post('/api/v1/cases', { headers: headers(), data: { full_name: `Synthetic Next Notification Patient ${Date.now()}`, age: 46, sex: 'male' } })
  expect(nextCase.status()).toBe(201)
  clinicalCase = await nextCase.json()
  await analyse()
  await expect(trigger).toHaveAttribute('aria-label', /o‘qilmagan/, { timeout: 10000 })
  await trigger.click()
  await panel.locator('.notification-center__item.is-unread').filter({ hasText: clinicalCase.alias }).first().click()
  await expect(page).toHaveURL(new RegExp(`/cases/${clinicalCase.id}$`))
  await expect(panel).toBeHidden()
  expect((await (await page.request.get('/api/v1/notifications')).json()).unread_count).toBe(0)
})
