"""billing_subscriptions"""

from alembic import op
import sqlalchemy as sa

revision = "20260918_billing"
down_revision = "1e90efbfb4f3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "billing_payment_methods",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("card_number", sa.String(length=40), nullable=False),
        sa.Column("recipient", sa.String(length=150), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "billing_plans",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("price_uzs", sa.Integer(), nullable=True),
        sa.Column("doctor_limit", sa.Integer(), nullable=True),
        sa.Column("period_months", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("is_custom", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "billing_clinics",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("plan_id", sa.String(length=50), nullable=True),
        sa.Column("plan_name", sa.String(length=100), nullable=False),
        sa.Column("doctor_limit", sa.Integer(), nullable=False),
        sa.Column("price_uzs", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("internal_demo", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["billing_plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id"),
    )
    op.create_table(
        "billing_user_profiles",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "billing_subscription_requests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("actor_id", sa.String(length=36), nullable=False),
        sa.Column("plan_id", sa.String(length=50), nullable=False),
        sa.Column("plan_name", sa.String(length=100), nullable=False),
        sa.Column("price_uzs", sa.Integer(), nullable=False),
        sa.Column("doctor_limit", sa.Integer(), nullable=False),
        sa.Column("payment_method_id", sa.String(length=36), nullable=False),
        sa.Column("payment_method_name", sa.String(length=100), nullable=False),
        sa.Column("payment_recipient", sa.String(length=150), nullable=False),
        sa.Column("payment_card_last4", sa.String(length=4), nullable=False),
        sa.Column("payment_reference", sa.String(length=120), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("receipt_name", sa.String(length=180), nullable=False),
        sa.Column("receipt_path", sa.String(length=250), nullable=False),
        sa.Column("receipt_mime", sa.String(length=50), nullable=False),
        sa.Column("receipt_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("review_note", sa.Text(), nullable=False),
        sa.Column("reviewer_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("granted_starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("granted_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_method_id"],
            ["billing_payment_methods.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["billing_plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["billing_clinics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("receipt_hash"),
    )
    op.create_index(
        op.f("ix_billing_subscription_requests_status"),
        "billing_subscription_requests",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_billing_subscription_requests_tenant_id"),
        "billing_subscription_requests",
        ["tenant_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_billing_subscription_requests_tenant_id"),
        table_name="billing_subscription_requests",
    )
    op.drop_index(
        op.f("ix_billing_subscription_requests_status"), table_name="billing_subscription_requests"
    )
    op.drop_table("billing_subscription_requests")
    op.drop_table("billing_user_profiles")
    op.drop_table("billing_clinics")
    op.drop_table("billing_plans")
    op.drop_table("billing_payment_methods")
    # ### end Alembic commands ###
